feature/DEMO-26+28
Anii555/API_OnlineShop_frontend pull request #1
Opened 2022-04-04 19:46 UTC by Anii555

2022-04-05 20:23 UTC, Corel-frim requested changes
Классный пулл реквест и код красивый, вопросов нет

2022-04-06 14:36 UTC, Corel-frim requested changes

2022-04-06 14:36 UTC, Corel-frim commented on src/App.vue
>        alert(
В таком случае лучше в консоль писать объект, так можно будет поля проверить

2022-04-06 14:36 UTC, Corel-frim commented on src/App.vue
>              this.response = JSON.stringify(rez.data); //для массива
А ой

2022-04-06 14:36 UTC, Corel-frim commented on src/App.vue
>          (this.response.unitPrice = "555"),
Некрасиво делать непонятно что и для чего

2022-04-06 14:36 UTC, Corel-frim commented on src/App.vue
>            body: this.response,
Нет

2022-04-06 14:36 UTC, Corel-frim commented on src/App.vue
> +      this.basket = currentProduct;
А если в корзине до этого были продукты, то что будет с ними?

2022-04-06 14:36 UTC, Corel-frim commented on src/App.vue
>          <h1>Корзинка</h1>
Рано

2022-04-06 14:36 UTC, Corel-frim commented on src/App.vue
> +                <td>{{ basket.name }}</td>
У массива нет таких полей

2022-04-06 15:03 UTC, Anii555 commented on src/App.vue
>              this.response = JSON.stringify(rez.data); //для массива
Что?

2022-04-06 15:04 UTC, Anii555 commented on src/App.vue
>          <h1>Корзинка</h1>
Рано заниматься фоном или что?

2022-04-06 16:10 UTC, Anii555 commented on src/App.vue
> +      this.basket = currentProduct;
Так задача стояла на возможность добавления выбранного товара в корзину, а не на сохранение ранее добавленных товаров)

2022-04-06 16:14 UTC, Anii555 commented on src/App.vue
>            body: this.response,
То была попытка отправить запрос на добавление на бэк, но задачи такой тоже не стояло, поэтому оставила на будущее..

2022-04-06 16:14 UTC, Anii555 commented on src/App.vue
>          (this.response.unitPrice = "555"),
Тот же мотив, что и у метода add()

2022-04-07 16:36 UTC, Corel-frim commented on src/App.vue
>              this.response = JSON.stringify(rez.data); //для массива
Убери JSON.stringify (и в целом этот метод, он тут быть не должен)

2022-04-07 16:38 UTC, Corel-frim commented on src/App.vue
>          (this.response.unitPrice = "555"),
Нет, писать код внутри скобок (как и хардкодить поля, которых **не должно быть у массива**) - нельзя

2022-04-07 16:38 UTC, Corel-frim commented on src/App.vue
>            body: this.response,
Не надо на будущее, удоли

2022-04-07 16:39 UTC, Corel-frim commented on src/App.vue
> +      this.basket = currentProduct;
Добавление в корзину делается через запрос на бек, а не хранение на фронте

2022-04-07 16:40 UTC, Corel-frim commented on src/App.vue
>          <h1>Корзинка</h1>
Рано корзину на фронте добавлять, была задача только на добавление в нее, а не показ ее содержимого

2022-04-07 16:40 UTC, Corel-frim commented on src/App.vue
> +                <td>{{ basket.name }}</td>
И не должно быть

2022-04-11 11:13 UTC, Corel-frim requested changes

2022-04-11 11:13 UTC, Corel-frim commented on src/App.vue
>          <h1>Корзинка</h1>
Все еще актуально

2022-04-11 11:13 UTC, Corel-frim commented on src/App.vue
> +                <td>{{ basket.name }}</td>
Убери использование этих полей

2022-04-11 11:13 UTC, Corel-frim commented on src/App.vue
>          <label v-bind="response">Добавленный элемент(?): {{ sel }}</label>
Не надо

2022-04-11 11:13 UTC, Corel-frim commented on src/App.vue
> +        },
Лучше базовый объект с null-значениями не создавать, чтобы не аффектнуло в будущем

2022-04-11 11:13 UTC, Corel-frim commented on src/App.vue
>        sel: null,
Если хочешь показать отсутствие значения - в js для этого используется undefined. Null у них - тоже значение

2022-04-11 11:13 UTC, Corel-frim commented on src/App.vue
> +      this.basket = {
Ты пытаешься из массива (а в data он объявлен именно как массив) сделать объект. Это очень неправильно. А еще на текущем этапе не надо сохранять корзину на фронте ни в каком виде

2022-04-11 11:13 UTC, Corel-frim commented on src/App.vue
> +      // const newProductOfBasket = {
Опять закомментированный код? 🙄

2022-04-11 11:13 UTC, Corel-frim commented on src/App.vue
> +      console.log(
Имелось ввиду, что можно написать console.log(this.basket), и все, а в самой консоли можно было бы уже смотреть, у каких полей какие значения

2022-04-11 11:13 UTC, Corel-frim commented on src/App.vue
> +        body: this.response,
Не должно быть body у этого запроса

2022-04-11 11:13 UTC, Corel-frim commented on src/App.vue
> +      this.basket = currentProduct;
Удали присвоение массиву ссылки на объект. Это очень некрасиво.

2022-04-11 11:13 UTC, Corel-frim commented on src/App.vue
> +      .get("http://localhost:5090/Product/GetAllProduct")
С маленькой буквы каждый элемент пути должен быть. И почему у тебя вдруг GetAllProduct появился? Красиво же до этого было и работало корректно, зачем менять-то

2022-05-18 10:18 UTC, Anii555 commented on src/App.vue
>        sel: null,
✅

2022-05-18 10:25 UTC, Anii555 commented on src/App.vue
>          <label v-bind="response">Добавленный элемент(?): {{ sel }}</label>
Что именно? Не вижу тут конкретики, только огрызок кода и непонятно к чему именно тут твой коммент
<img width="604" alt="image" src="https://user-images.githubusercontent.com/43905248/169017897-6824a09e-641e-42a6-b0d1-7dae8f2390b2.png">

2022-05-18 14:14 UTC, Anii555 commented on src/App.vue
>          <h1>Корзинка</h1>
✅

2022-05-18 14:25 UTC, Anii555 commented on src/App.vue
> +        body: this.response,
✅

2022-05-18 14:51 UTC, Anii555 commented on src/App.vue
> +      .get("http://localhost:5090/Product/GetAllProduct")
Для того, чтобы не путать методы вызова **всего** списка, с запросом по id и пр., или больше подобных и не будет?

2022-05-20 14:26 UTC, Corel-frim commented on src/App.vue
> +      .get("http://localhost:5090/Product/GetAllProduct")
Да не должно быть в целом, только если в другом контроллере, но тогда и в пути "product" поменяется
И напиши "Product" с маленькой буквы все-таки 😅

2022-05-20 14:26 UTC, Corel-frim approved these changes

2022-05-21 12:29 UTC, merged