DEMO-28
Anii555/API_OnlineShop_frontend pull request #3
Opened 2022-05-23 17:18 UTC by Anii555

2022-05-23 17:34 UTC, Corel-frim commented on src/App.vue
> +                    <!-- Начало удачной вставки-->
Кхм

2022-05-23 17:34 UTC, Corel-frim commented on src/App.vue
> +                <!-- Конец удачной вставки-->
Кхм 2

2022-05-23 17:40 UTC, Corel-frim requested changes

2022-05-23 17:40 UTC, Corel-frim commented on src/App.vue
> +                      {{ "Информация о продукте" }}
В фигурных скобках код пишут, а константный текст можно (читай - нужно) и без них

2022-05-23 17:40 UTC, Corel-frim commented on src/App.vue
> +                  v-for="item in itemsPerPage"
v-for тут не нужен (как и :key)

2022-05-23 17:40 UTC, Corel-frim commented on src/App.vue
> +      sel: [],
Опять sel стал массивом, а ниже вдруг становится объектом. Непорядок

2022-05-24 07:53 UTC, Anii555 commented on src/App.vue
> +                    <!-- Начало удачной вставки-->
Всё нужное!

2022-05-24 07:53 UTC, Anii555 commented on src/App.vue
> +                <!-- Конец удачной вставки-->
Всё нужное! 2

2022-05-24 07:53 UTC, Anii555 commented on src/App.vue
> +                      {{ "Информация о продукте" }}
✅

2022-05-24 07:53 UTC, Anii555 commented on src/App.vue
> +                  v-for="item in itemsPerPage"
✅

2022-05-24 07:53 UTC, Anii555 commented on src/App.vue
> +      sel: [],
✅

2022-05-24 08:50 UTC, Corel-frim requested changes

2022-05-24 08:50 UTC, Corel-frim commented on src/App.vue
> +                      "Информация о продукте"
Убери скобочки, они не нужны, это же разметка чистая, а не код)

2022-05-24 08:50 UTC, Corel-frim commented on src/App.vue
> +            :items-per-page.sync="itemsPerPage"
*Просто комментарий* шота больше 1 товара показывается, и страниц нет

2022-05-24 08:55 UTC, Anii555 commented on src/App.vue
> +                      "Информация о продукте"
А, всм кавычки?

2022-05-24 08:56 UTC, Anii555 commented on src/App.vue
> +                      "Информация о продукте"
✅

2022-05-24 09:05 UTC, Corel-frim approved these changes

2022-05-24 09:10 UTC, merged