Demo 35
Anii555/API_OnlineShop_frontend pull request #5
Opened 2022-06-20 15:21 UTC by Anii555

2022-06-20 15:34 UTC, Corel-frim requested changes

2022-06-20 15:34 UTC, Corel-frim commented on src/App.vue
> +                      <!-- Начало удачной вставки-->
Вот это дублируется с тем, что было на строке 66

2022-06-21 19:21 UTC, Anii555 commented on src/App.vue
> +                      <!-- Начало удачной вставки-->
Вынесла в компонент

2022-06-28 16:46 UTC, Corel-frim requested changes

2022-06-28 16:46 UTC, Corel-frim commented on src/components/CartProducts.vue
> +    showCartItem() {
showCartItem или updateCart?

2022-06-28 16:46 UTC, Corel-frim commented on src/components/CartProducts.vue
> +    clearCartItem() {
Лучше просто clearCart

2022-06-28 16:46 UTC, Corel-frim commented on src/components/CartProducts.vue
> +          this.response = null;
[]

2022-06-28 16:46 UTC, Corel-frim commented on src/components/CartProducts.vue
> +  }, */
Комментики убираем

2022-06-28 16:46 UTC, Corel-frim commented on src/components/CartProducts.vue
> +                    <td>{{ item.productName }}</td>
В item нет такого поля, там только key и value (а должно быть product и amount, что тоже не productName и ему подобные)

2022-06-28 16:46 UTC, Corel-frim commented on src/App.vue
> +                <v-col cols="12" sm="4" md="2" lg="5">
На будущее: это можно вынести в общий элемент и использовать здесь и для корзины

2022-06-28 16:46 UTC, Corel-frim commented on src/App.vue
> +                                    $refs.cartProd.showCartItem()
Не надо так(

2022-06-28 16:46 UTC, Corel-frim commented on src/App.vue
> +                    $refs.cartProd.toggleCart(), $refs.cartProd.showCartItem()
Лучше объединить

2022-06-28 16:46 UTC, Corel-frim commented on src/App.vue
> +                    addInBasket(item.productId), $refs.cartProd.showCartItem()
Не надо так(

2022-06-28 16:46 UTC, Corel-frim commented on src/components/CartProducts.vue
> +                  {{ sel.productId }}
Нигде sel не задается, по нему информация не появляется в корзине, как это происходит в списке товаров

2022-06-29 09:49 UTC, Anii555 commented on src/components/CartProducts.vue
> +  }, */
✅

2022-06-29 09:50 UTC, Anii555 commented on src/components/CartProducts.vue
> +          this.response = null;
✅

2022-06-29 09:59 UTC, Anii555 commented on src/components/CartProducts.vue
> +    clearCartItem() {
✅

2022-06-29 10:00 UTC, Anii555 commented on src/components/CartProducts.vue
> +    showCartItem() {
Сделала updateCart, да ✅

2022-06-29 10:02 UTC, Anii555 commented on src/components/CartProducts.vue
> +                  {{ sel.productId }}
Это из родительской версии компонента осталось, ещё ничего с этим не делала, возможно этот блок вообще уберу (хотя пусть будет наверное)

2022-07-01 15:05 UTC, Anii555 commented on src/components/CartProducts.vue
> +                    <td>{{ item.productName }}</td>
Сделаноо~~~✅

2022-07-01 15:08 UTC, Anii555 commented on src/App.vue
> +                                    $refs.cartProd.showCartItem()
✅

2022-07-01 15:08 UTC, Anii555 commented on src/App.vue
> +                    $refs.cartProd.toggleCart(), $refs.cartProd.showCartItem()
✅

2022-07-01 15:08 UTC, Anii555 commented on src/App.vue
> +                    addInBasket(item.productId), $refs.cartProd.showCartItem()
✅

2022-07-05 18:38 UTC, Corel-frim commented on src/components/CartProducts.vue
> +      this.cart_sum = this.cart_sum.reduce((sum, current) => {
{ return sum + current; } можно поменять на просто sum + current

2022-07-05 18:39 UTC, Corel-frim commented on src/components/CartProducts.vue
> +                  {{ sel.productId }}
Или можно задавать sel, чтобы было красиво

2022-07-05 18:40 UTC, Corel-frim requested changes
Ждем

2022-07-05 19:06 UTC, Anii555 commented on src/components/CartProducts.vue
> +      this.cart_sum = this.cart_sum.reduce((sum, current) => {
Сделано, но это мелочи, там проблема в другом........ в emit и props нужна help

2022-07-12 21:06 UTC, Corel-frim approved these changes

2022-07-13 11:15 UTC, merged