DEMO-37
Anii555/API_OnlineShop_frontend pull request #6
Opened 2022-07-13 18:00 UTC by Anii555

2022-07-13 21:36 UTC, Corel-frim requested changes
А CartProducts.vue?

2022-07-13 21:36 UTC, Corel-frim commented on src/App.vue
> -      axios.post(`http://localhost:5090/cart/${id}`).then(() => {
В апи должен уйти только запрос, т.е. axios.post(...), а then и пр. остаться тут

2022-07-13 21:36 UTC, Corel-frim commented on src/App.vue
> -      .get("http://localhost:5090/product/getAllProducts")
Вот эти 2 строки должны уйти в апи, все что ниже - остаться

2022-07-13 21:36 UTC, Corel-frim commented on src/cartApi.js
> +  axios.post(`http://localhost:5090/cart/${id}`).then(() => {
return не стоит забывать, поскольку это асинхронный запрос, они в js построены на промисах (типа как Task в шарпе)
И должно остаться только axios.post(...)
Имеет смысл вынести `http://localhost:5090/cart/` в константу в апи, поскольку внутри апи оно должно использоваться несколько раз

2022-07-13 21:36 UTC, Corel-frim commented on src/cartApi.js
> +const axios = require("axios").default;
Переделать на import

2022-07-13 21:36 UTC, Corel-frim commented on src/productsApi.js
> +mounted: function getAllProducts() {
mounted тут быть не должно, в остальном замечания те же, что и к cartApi

2022-07-13 21:36 UTC, Corel-frim commented on src/productsApi.js
> +  this.$root.$on(`cart_sum`, this.changeSum);
Эта строка не нужна вообще в проекте, т.к. уже используется @cart_sum

2022-07-14 07:31 UTC, Anii555 commented on src/cartApi.js
> +const axios = require("axios").default;
✅

2022-07-14 07:31 UTC, Anii555 commented on src/productsApi.js
> +mounted: function getAllProducts() {
✅

2022-07-14 08:50 UTC, Anii555 commented on src/productsApi.js
> +  this.$root.$on(`cart_sum`, this.changeSum);
✅

2022-07-14 09:53 UTC, Anii555 commented on src/App.vue
> -      axios.post(`http://localhost:5090/cart/${id}`).then(() => {
✅

2022-07-14 09:53 UTC, Anii555 commented on src/App.vue
> -      .get("http://localhost:5090/product/getAllProducts")
✅

2022-07-14 13:09 UTC, Anii555 commented on src/App.vue
> -      axios.post(`http://localhost:5090/cart/${id}`).then(() => {
✅

2022-07-14 14:29 UTC, Anii555 commented on src/cartApi.js
> +  axios.post(`http://localhost:5090/cart/${id}`).then(() => {
✅

2022-07-16 15:53 UTC, Corel-frim requested changes

2022-07-16 15:53 UTC, Corel-frim commented on src/components/CartProducts.vue
> +import cartApi from "./API_OnlineShop_frontend/src/cartApi.js";
А разве не ../cartApi?

2022-07-16 15:53 UTC, Corel-frim commented on src/cartApi.js
> +  return axios.post(path_cart + `${id}`);
Можно просто path_cart + id

2022-07-16 15:53 UTC, Corel-frim commented on src/cartApi.js
> +  return axios.delete(path_cart + `${id}`);
Можно просто path_cart + id

2022-07-16 15:53 UTC, Corel-frim commented on src/cartApi.js
> +export function updateCart() {
Так это же не обновление

2022-07-19 13:19 UTC, Anii555 commented on src/components/CartProducts.vue
> +import cartApi from "./API_OnlineShop_frontend/src/cartApi.js";
✅

2022-07-19 13:22 UTC, Anii555 commented on src/cartApi.js
> +  return axios.post(path_cart + `${id}`);
✅

2022-07-19 13:22 UTC, Anii555 commented on src/cartApi.js
> +  return axios.delete(path_cart + `${id}`);
✅

2022-07-19 13:39 UTC, Corel-frim commented on src/components/CartProducts.vue
>            console.log(resp_cart.data);
И удалить все записи в консоль не забудь

2022-07-19 13:53 UTC, Anii555 commented on src/components/CartProducts.vue
>            console.log(resp_cart.data);
✅

2022-07-19 14:12 UTC, Anii555 commented on src/cartApi.js
> +export function updateCart() {
✅

2022-07-19 14:14 UTC, Corel-frim approved these changes

2022-07-19 14:27 UTC, merged